name: gedit
adopt-info: gedit
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0:
    symlink: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/peas-demo:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/peas-demo
  /usr/share/gedit:
    symlink: $SNAP/usr/share/gedit

slots:
  # for GtkApplication registration
  gedit:
    interface: dbus
    bus: session
    name: org.gnome.gedit

apps:
  gedit:
    command: usr/bin/gedit
    extensions: [gnome-3-38]
    plugs:
      - avahi-observe
      - cups-control
      - home
      - network
      - mount-observe
      - removable-media
    common-id: org.gnome.gedit.desktop
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0

parts:
  amtk:
    source: https://gitlab.gnome.org/GNOME/amtk.git
    source-type: git
    source-tag: 5.2.0
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-introspection=yes
    organize:
      snap/gedit/current/usr: usr
    build-packages:
      - gnome-common
      - gtk-doc-tools

  tepl:
    after: [amtk]
    source: https://gitlab.gnome.org/GNOME/tepl.git
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    organize:
      snap/gedit/current/usr: usr
    build-packages:
      - libuchardet-dev

  gedit:
    after: [tepl]
    source: https://gitlab.gnome.org/GNOME/gedit.git
    source-branch: gnome-41
    source-type: git
    parse-info: [usr/share/metainfo/org.gnome.gedit.appdata.xml]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Dvala_args="--vapidir=$SNAPCRAFT_STAGE/usr/share/vala/vapi"
    build-environment:
      - C_INCLUDE_PATH: $SNAPCRAFT_STAGE/usr/include/gtksourceview-4
    override-build: |
       sed -i.bak -e 's|Icon=org.gnome.gedit$|Icon=${SNAP}/meta/gui/org.gnome.gedit.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.gedit.desktop.in
       sed -i.bak -e "s|symlink_media: true|symlink_media: false|g" $SNAPCRAFT_PART_SRC/help/meson.build
       snapcraftctl build
       mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp  $SNAPCRAFT_PART_SRC/data/icons/org.gnome.gedit.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
       cp $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.gnome.gedit.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)

  gedit-plugins:
    after: [gedit]
    source: https://gitlab.gnome.org/GNOME/gedit-plugins.git
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/snap/gedit/current/usr
      - -Dplugin_bookmarks=true
      - -Dplugin_bracketcompletion=true
      - -Dplugin_charmap=true
      - -Dplugin_codecomment=true
      - -Dplugin_colorpicker=true
      - -Dplugin_colorschemer=true
      - -Dplugin_commander=false
      - -Dplugin_drawspaces=true
      - -Dplugin_findinfiles=false
      - -Dplugin_git=true
      - -Dplugin_joinlines=true
      - -Dplugin_multiedit=false
      - -Dplugin_smartspaces=true
      - -Dplugin_terminal=true
      - -Dplugin_textsize=true
      - -Dplugin_translate=true
      - -Dplugin_wordcompletion=true
    organize:
      snap/gedit/current/usr: usr
    build-environment:
      - C_INCLUDE_PATH: $SNAPCRAFT_STAGE/usr/include:$SNAPCRAFT_STAGE/usr/include/gedit-3.14:$SNAPCRAFT_STAGE/usr/include/gtksourceview-4
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gedit
      - PKG_CONFIG_PATH: $PKG_CONFIG_PATH:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
    build-packages:
      - libgit2-glib-1.0-dev
      - libgucharmap-2-90-dev
      - libvte-2.91-dev
      - yelp-tools

  libraries:
    plugin: nil
    stage-packages:
      - libuchardet0
      - libfribidi0
    prime:
      - usr/lib/*/libuchardet*
      - usr/lib/*/libfribidi*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [gedit-plugins, libraries]
    plugin: nil
    build-snaps: [core20, gtk-common-themes, gnome-3-38-2004/latest/candidate]
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
